FROM openjdk:17-jdk-alpine3.14
COPY --from=builder ./build/libs/app.jar /
CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
